### ISSUE TITLE
能否增加备选BASE_URL功能

### ISSUE THREAD

**Issue by Zhou-Shilin** [KroMiose/nonebot_plugin_naturel_gpt#199]
我在多个中转站都买了key，有几个很便宜但不是很稳定，我想优先使用某个中转站的key，如果失败则转为使用稳定中转站的key。
可以添加一个类似这样的配置嘛
```yaml
OPENAI_API:
  - API_KEY: sk-xxxxxxxxxxxxxxx
    BASE_URL: 'https://api.example.com/v1'
  - API_KEY: sk-xxxxxxxxxxxxxxx
    BASE_URL: 'https://api.example2.com/v1' # BASE_URL可以和上一项不同
  - API_KEY: sk-xxxxxxxxxxxxxxx
    BASE_URL: 'https://api.example3.com/v1'
  - API_KEY: sk-xxxxxxxxxxxxxxx
    BASE_URL: 'https://api.example3.com/v1' # 也可以和上一项一样
```
