### ISSUE TITLE
开启扩展后无限reload

### ISSUE THREAD

**Issue by Feiyuyu0503** [KroMiose/nonebot_plugin_naturel_gpt#33]
插件版本v1.5.2, 设置 NG_ENABLE_EXT: true 时，会报warning，然后无限重复reload
```
03-07 14:27:07 [WARNING] uvicorn | WatchFiles detected changes in 'data/naturel_gpt/extensions/Extension.py', 'ext_cache/Extension.py', 'ext_cache/__init__.py'. Reloading...
03-07 14:27:08 [SUCCESS] nonebot | NoneBot is initializing...
```

naturel_gpt_config.yml 部分内容如下
```
NG_ENABLE_EXT: true
NG_ENABLE_MSG_SPLIT: true
NG_EXT_LOAD_LIST:
- EXT_NAME: ext_remember
  IS_ACTIVE: true
- EXT_NAME: ext_forget
  IS_ACTIVE: true
- EXT_NAME: ext_random_pic
  IS_ACTIVE: true
```
